export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  PRISMA = 'PRISMA_SERVICE',
  USER = 'USER_SERVICE',
  PROJECT = 'PROJECT_SERVICE',
  TASK = 'TASK_SERVICE',
  CRYPTO = 'CRYPTO_SERVICE',
  CONFIG = 'CONFIG_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
}

export enum EVENTS {
  TASK_ASSIGNED = 'task.assigned',
  PROJECT_INVITED = 'project.invited',
}
