export enum SERVICES {
  AUTH = 'AUTH_SERVICE',
  PRISMA = 'PRISMA_SERVICE',
  USER = 'USER_SERVICE',
  PROJECT = 'PROJECT_SERVICE',
  TASK = 'TASK_SERVICE',
  CRYPTO = 'CRYPTO_SERVICE',
  CONFIG = 'CONFIG_SERVICE',
  NOTIFICATION = 'NOTIFICATION_SERVICE',
  DECRYPT = 'DECRYPT_SERVICE',
}

export enum ERROR_CODES {
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
  UNAUTHORIZED = 'UNAUTHORIZED',
  INTERNAL_SERVER_ERROR = 'INTERNAL_SERVER_ERROR',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
  INVALID_ROLE = 'INVALID_ROLE',
  INVALID_STATUS = 'INVALID_STATUS',
  MISSING_AUTH_TOKEN = 'MISSING_AUTH_TOKEN',
  INVALID_OR_EXPIRED_TOKEN = 'INVALID_OR_EXPIRED_TOKEN',
  INCORRECT_PASSWORD = 'INCORRECT_PASSWORD',
  NEW_PASSWORD_NOT_DIFFERENT = 'NEW_PASSWORD_NOT_DIFFERENT',
  NEW_PASSWORDS_DIFFERENT = 'NEW_PASSWORDS_DIFFERENT',
}

export enum USER_DTO_ERROR_CODES {
  STATUS_ENUM = 'STATUS_ENUM',
  THEME_ENUM = 'THEME_ENUM',
  IS_BOOLEAN = 'IS_BOOLEAN',
  IS_STRING = 'IS_STRING',
  IS_NOT_EMPTY = 'IS_NOT_EMPTY',
  ALIAS_TOO_LONG = 'ALIAS_TOO_LONG',
  IS_EMAIL = 'IS_EMAIL',
  EMAIL_TOO_LONG = 'EMAIL_TOO_LONG',
  PASSWORD_TOO_SHORT = 'PASSWORD_TOO_SHORT',
  PASSWORD_TOO_LONG = 'PASSWORD_TOO_LONG',
}

export enum TASK_DTO_ERROR_CODES {
  REQUIRED_ID = 'REQUIRED_ID',
  INVALID_ID = 'INVALID_ID',
  ID_TOO_LONG = 'ID_TOO_LONG',

  INVALID_STATE = 'INVALID_STATE',
  INVALID_PRIORITY = 'INVALID_PRIORITY',

  REQUIRED_TITLE = 'REQUIRED_TITLE',
  INVALID_TITLE = 'INVALID_TITLE',
  TITLE_TOO_LONG = 'TITLE_TOO_LONG',

  INVALID_DESCRIPTION = 'INVALID_DESCRIPTION',
  DESCRIPTION_TOO_LONG = 'DESCRIPTION_TOO_LONG',

  REQUIRED_INITIAL_DATE = 'REQUIRED_INITIAL_DATE',
  INVALID_INITIAL_DATE = 'INVALID_INITIAL_DATE',

  REQUIRED_DUE_DATE = 'REQUIRED_DUE_DATE',
  INVALID_DUE_DATE = 'INVALID_DUE_DATE',
  DUE_DATE_BEFORE_INITIAL_DATE = 'DUE_DATE_BEFORE_INITIAL_DATE',

  REQUIRED_PROJECT_ID = 'REQUIRED_PROJECT_ID',
  INVALID_PROJECT_ID = 'INVALID_PROJECT_ID',
  PROJECT_ID_TOO_LONG = 'PROJECT_ID_TOO_LONG',

  INVALID_ASSIGNED_USER_ID = 'INVALID_ASSIGNED_USER_ID',
  ASSIGNED_USER_ID_TOO_LONG = 'ASSIGNED_USER_ID_TOO_LONG',
}

export enum PROJECT_DTO_ERROR_CODES {
  REQUIRED_ID = 'REQUIRED_ID',
  INVALID_ID = 'INVALID_ID',
  ID_TOO_LONG = 'ID_TOO_LONG',

  REQUIRED_NAME = 'REQUIRED_NAME',
  INVALID_NAME = 'INVALID_NAME',
  NAME_TOO_LONG = 'NAME_TOO_LONG',

  INVALID_DESCRIPTION = 'INVALID_DESCRIPTION',
  DESCRIPTION_TOO_LONG = 'DESCRIPTION_TOO_LONG',

  REQUIRED_CATEGORY = 'REQUIRED_CATEGORY',
  INVALID_CATEGORY = 'INVALID_CATEGORY',
}

export enum PROJECT_ERROR_CODES {
  OWNER_CANNOT_REMOVE_SELF = 'OWNER_CANNOT_REMOVE_SELF',
}

export enum PROJECT_GUARD_ERROR_CODES {
  MISSING_PROJECT_ID = 'MISSING_PROJECT_ID',
  NOT_A_MEMBER = 'NOT_A_MEMBER',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
}

export enum MEMBER_DTO_ERROR_CODES {
  REQUIRED_ROLE = 'REQUIRED_ROLE',
  INVALID_ROLE = 'INVALID_ROLE',
}

export enum NOTIFICATION_ERROR_CODES {
  INVITE_ALREADY_EXISTS = 'INVITE_ALREADY_EXISTS',
}

export enum PROJECT_MEMBER_GUARD_ERROR_CODES {
  USER_NOT_IN_REQUEST = 'USER_NOT_IN_REQUEST',
  MISSING_PROJECT_ID = 'MISSING_PROJECT_ID',
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
}

export enum PROJECT_SERVICE_ERROR_CODES {
  USER_NOT_FOUND_BY_EMAIL = 'USER_NOT_FOUND_BY_EMAIL',
  PROJECT_NOT_FOUND = 'PROJECT_NOT_FOUND',

  USER_ALREADY_INVITED = 'USER_ALREADY_INVITED',
  USER_ALREADY_MEMBER = 'USER_ALREADY_MEMBER',
}

export enum PROJECT_ADMIN_GUARD_ERROR_CODES {
  MISSING_PROJECT_ID_PARAM = 'MISSING_PROJECT_ID_PARAM',
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
}

export enum PROJECT_OWNER_GUARD_ERROR_CODES {
  MISSING_PROJECT_ID_PARAM = 'MISSING_PROJECT_ID_PARAM',
  MEMBERSHIP_NOT_FOUND = 'MEMBERSHIP_NOT_FOUND',
  INSUFFICIENT_ROLE = 'INSUFFICIENT_ROLE',
}

export enum TASK_GUARD_ERROR_CODES {
  USER_NOT_IN_REQUEST = 'USER_NOT_IN_REQUEST',

  TASK_ID_MISSING = 'TASK_ID_MISSING',
  TASK_NOT_FOUND = 'TASK_NOT_FOUND',

  FORBIDDEN = 'FORBIDDEN',
}

export enum AUTH_ERROR_CODES {
  INVALID_CREDENTIALS = 'INVALID_CREDENTIALS',
  USER_ALREADY_EXISTS = 'USER_ALREADY_EXISTS',
}

export enum RESPONSES {
  LOGGED_IN = 'LOGGED_IN',
  LOGGED_OUT = 'LOGGED_OUT',
  REGISTER_SUCCESS = 'REGISTER_SUCCESS',
}
